#!/bin/bash

xrandr --output eDP-1 --off --output DP-1 --off --output HDMI-1 --off --output DP-2 --off --output DP-3 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-4 --off --output DP-5 --off
xwallpaper --zoom ~/Pictures/Wallpapers/girl_train.jpg
pkill polybar
nohup polybar -q topexternal -c ~/.config/polybar/hack/config.ini &
bspc monitor DP-3 -d 1 2 3 4 5 6 7
bspc monitor eDP-1 -d 9
pkill conky
conky -c ~/Code/todo.conky/todo/todo.lua > /dev/null 2>&1
